CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Clients import views
from Clients.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers_list/', views.CustomersListView),
    path('add_customer/', views.CustomerAddView.as_view()),
    path('edit_customer/<pk>', views.CustomerUpdateView.as_view()),
    path('delete_customer/<pk>', views.CustomerDeleteView.as_view()),
    path('', TemplateView.as_view(template_name='basic_page.html'), name='home'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls')),
    path('calendar/', include('Calendar.urls')),
    ### Product
    path('products_list/', views.ProductsListView),
    path('add_product/', views.ProductAddView.as_view()),
    path('edit_product/<pk>', views.ProductUpdateView.as_view()),
    path('delete_product/<pk>', views.ProductDeleteView.as_view()),
    ### Order
    path('orders/', views.OrdersListView),
    path('add_order/', views.OrderAddView.as_view()),
    path('edit_order/<pk>', views.OrderEditView.as_view()),
    path('order/<int:id>/', views.OrderAddLinesView.as_view()),
    path('delete_line/<pk>', views.OrderLineDeleteView.as_view()),
    path('pdf_generate/<int:id>', views.PDF_render_view.as_view()),

    path('map/', TemplateView.as_view(template_name='map.html'), name='map'),
]

Clients/models.py
from django.core.validators import MinValueValidator
from django.db import models
from phone_field import PhoneField

from Calendar.models import Event

customers_statuses = (
    (1, "Active"),
    (2, "Suspended"),
    (3, "Inactive"),
    (4, "VIP"))


class Customer(models.Model):
    customer_number = models.AutoField(primary_key=True, verbose_name='Customer ID')
    first_name = models.CharField(max_length=65, verbose_name='First name')
    last_name = models.CharField(max_length=65, verbose_name='Last name')
    phone = PhoneField()
    e_mail = models.EmailField(max_length=65, verbose_name="E-mail")
    address = models.CharField(max_length=65, verbose_name='Address')
    city = models.CharField(max_length=65, verbose_name='City')
    zip = models.CharField(max_length=6, verbose_name='Zip code')
    company = models.CharField(max_length=240, null=True, verbose_name='Company')
    status = models.IntegerField(choices=customers_statuses, default="1", verbose_name='Status')
    website = models.URLField(null=True, default="https:/")

    def __str__(self):
        return self.company


order_statuses = (
    (1, "Completed"),
    (2, "Open"),
    (3, "Suspended"),
    (4, "Canceled"),
    (5, "Closed"),

)


class Category(models.Model):
    category_name = models.TextField(max_length=20)
    category_id = models.AutoField(primary_key=True, serialize=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    product_id = models.AutoField(primary_key=True, serialize=True)
    product_name = models.CharField(max_length=20)
    product_price = models.FloatField(validators=[MinValueValidator(1, message='Minimum value = 10')])
    product_stock = models.IntegerField(validators=[MinValueValidator(1, message='Minimum value = 1')])
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_name


taxes = (
    (1, 0.00),
    (2, 0.05),
    (3, 0.08),
    (4, 0.23),
)

invoices_days = (
    (1, 14),
    (2, 30),
    (3, 60),

)


class Order(models.Model):
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Company')
    date = models.DateTimeField(auto_now_add=True)
    tax = models.IntegerField(choices=taxes)
    invoices_days = models.IntegerField(choices=invoices_days)
    status = models.IntegerField(choices=order_statuses)

    def __str__(self):
        return str(self.customer_id)


class OrderLine(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='ordertoline')
    product_selected = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Product")
    product_selected_name = models.CharField(max_length=50)
    quantity = models.IntegerField(validators=[MinValueValidator(1, message='Minimum quantity = 1')])
    total = models.DecimalField(max_digits=19, decimal_places=2)


class TextBox(models.Model):
    text = models.CharField(max_length=10240)

    def __str__(self):
        return self.text

templates/order/add_order.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">

        {% csrf_token %}
        <label><h4 class="m-0 font-weight-bold text-primary">New order</h4></label>
        <div style="text-align: right;">
            {{ form.as_p }}
        </div>
        <button class="btn btn-success btn-circle" type="submit" style="float: right"> <i class="fas fa-check"></i>
        </button>
    <a href="/orders/" style="float: inherit">
                    <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/return-62-563580.png" height=40px">
                  </a>
    </form>
{% endblock %}

templates/order/addorderlines.html
{% extends 'base.html' %}

{% block content %}

    <a href="/pdf_generate/{{ order.id }}"><img src="https://img.pngio.com/pdf-icon-png-image-with-transparent-background-toppng-pdf-icon-png-840_859.png" style="height: 40px"></a>
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

        <thead>
        <tr>
            <th>Order number</th>
            <th>Customer</th>
            <th>Order date</th>
            <th>Invoice date</th>
            <th>Tax rate:</th>
            <th>Status</th>
            <th>NET order value</th>
            <th>GROSS order value</th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.customer_id }}</td>
            <td>{{ order.date }}</td>
            <td>{{ order.get_invoices_days_display }}</td>
            <td>{{ order.get_tax_display }}</td>
            <td>{{ order.get_status_display }}</td>
            <td>{{order_net_value}}</td>
            <td>{{ order_gross_value }}</td>

        </tr>
        </tbody>
    </table>

    {% if order.status == 2 %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>{{ text }}</div>
            <input type="submit" value="Add to order">

        </form>
        <table class="table table-bordered" id="dataTable" width="80%" cellspacing="0">

            <thead>
            <tr>
                <th>Product ID</th>
                <th>Product name</th>

                <th>Quantity</th>
                <th>Total price</th>
            </tr>
            </thead>
            {% for line in lines %}

                <tbody>

                <tr>
                    <td>{{ line.product_selected_id }}</td>
                    <td>{{ line.product_selected_name }}</td>
                    <td>{{ line.quantity }}</td>
                    <td>{{ line.total }}</td>
                    <td><a href="/delete_line/{{ line.id}}"
                                   class="btn btn-danger btn-circle"><i class="fas fa-trash"></i></a></td>
                        </tr>
                </tr>
            {% endfor %}


            </tbody>

        </table>
    {% endif %}
{% endblock %}

templates/order/delete_orderline.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">

        {% csrf_token %}
        <label><h4 class="m-0 font-weight-bold text-primary">Do you really want to delete this record ?</h4></label>
        <div style="text-align: right;">
            {{ form.as_p }}
        </div>
        <button class="btn btn-success btn-circle" type="submit" style="float: right"> <i class="fas fa-check"></i>
        </button>
    <a href="/orders/"  style="float: inherit">
                    <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/return-62-563580.png" height=40px">
                  </a>
    </form>
{% endblock %}

templates/order/edit_order.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">

        {% csrf_token %}
        <label><h4 class="m-0 font-weight-bold text-primary">Edit order</h4></label>
        <div style="text-align: right;">
            {{ form.as_p }}
        </div>
        <button class="btn btn-success btn-circle" type="submit" style="float: right"> <i class="fas fa-check"></i>
        </button>
    <a href="/orders/" style="float: inherit">
                    <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/return-62-563580.png" height=40px">
                  </a>
    </form>
{% endblock %}

templates/order/orders_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">List of orders</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                    <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Customer ID</th>
                        <th>Company</th>
                        <th>Status</th>
                        <th>Order date</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Order ID</th>
                        <th>Customer ID</th>
                        <th>Company</th>
                        <th>Status</th>
                        <th>Order date</th>
                    </tr>
                    </tfoot>
                    <tbody>

                    {% for order in orders %}

                        <tr>
                            <td><a href="/edit_order/{{ order.id}}">{{ order.id }}</a></td>
                            <td>{{ order.customer_id.customer_number }}</td>
                            <td>{{ order.customer_id.company }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.date }}</td>


                            <td><a href="/order/{{ order.id }}"><img  src="https://getdrawings.com/free-icon/details-icon-png-64.png" height=40px></a></td>

                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <p><a href="/add_order/" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
        <span class="text">Add order</span>
    </a></p>





{% endblock %}